name: Autosar Workflow
on:
  push:
    branches:
      - main
jobs:
  Dummy_Rte_Generation: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Dummy RTE Generation
        run: echo "Running Dummy RTE Generation process..."
  ACG_Autosar:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run ACG Autosar Process
        run: echo "Running ACG Autosar process..."
  ELE_Generation:
    needs:
      - Dummy_Rte_Generation
      - ACG_Autosar
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Code
      run: echo "Checking out repo"
