name: common
on:
  workflow_call:
jobs:
  Dummy_Rte_Generation: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Dummy RTE Generation
        run: echo "Running Dummy RTE Generation process..."
  FOTA_init_Code_Generation:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run ACG Autosar Process
        run: echo "Running ACG Autosar process..."
  ELF_Generation:
    needs:
      - Dummy_Rte_Generation
      - FOTA_init_Code_Generation
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Code
      run: echo "Checking out repo"
