name: Exercise 1
on: push
jobs:
  demploy:
    runs-on: ubuntu-latest
    steps:
      -name: Get Code
      uses: actions/checkout@v3
      -name: Install Depenedecies
      run: npm ci
      -name: lint
      run: npm run lint
      -name: test
      run: npm run test
      -name: build
      run: nmp run build
      -name: Deploy
      run: echo "Deploying ..."
